runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /app
    static_files: public/app/index.html
    upload: public/app/index.html
    secure: always
    http_headers:
      Cache-Control: max-age=300

  - url: /
    static_files: public/index.html
    upload: public/index.html
    secure: always
    http_headers:
      Cache-Control: max-age=300

  - url: /(.+)
    static_files: public/\1
    upload: public/(.*)
    secure: always
    http_headers:
      Cache-Control: max-age=300
