defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:10.5.0

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Npx
          command: yarn global add npx
      - run:
          name: Install dependencies with yarn workspaces
          command: npx lerna bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "lerna.json"}}
          paths:
            - node_modules
            - packages/common/node_modules
            - packages/extension-chrome/node_modules
            - packages/extension-frontend/node_modules
            - packages/gae-api/node_modules
            - packages/gae-www-site/node_modules
            - packages/shared-components/node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "lerna.json"}}
      - run:
          name: "Execute tests"
          command: npx lerna run test
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "lerna.json"}}
      - run:
          name: Build Packages in parallel
          command: |
            yarn build
      - persist_to_workspace:
          root: packages
          paths:
            - common/dist
            - extension-chrome/dist
            - extension-frontend/dist
            - gae-api/dist
            - gae-www-site/public
            - gae-www-site/.cache
            - shared-components/dist
  deploy-chrome-extension:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: packages
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "lerna.json"}}
      - run:
          name: Upload to webstore
          command: npx chrome-webstore-upload-cli upload --source packages/extension-chrome/dist/chrome --extension-id $WEBSTORE_EXTENSION_ID --client-id $WEBSTORE_CLIENT_ID --client-secret $WEBSTORE_CLIENT_SECRET --refresh-token $WEBSTORE_REFRESH_TOKEN
      - run:
          name: Publish to webstore
          command: npx chrome-webstore-upload-cli publish --extension-id $WEBSTORE_EXTENSION_ID --client-id $WEBSTORE_CLIENT_ID --client-secret $WEBSTORE_CLIENT_SECRET --refresh-token $WEBSTORE_REFRESH_TOKEN
  deploy-frontend:
    <<: *defaults
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - attach_workspace:
          at: packages
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "lerna.json"}}
      - run:
          command: |
            echo $CLIENT_SECRET | base64 --decode > ${HOME}/client-secret.json
            gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
      - run:
          name: Set project default
          command: gcloud config set project $GCLOUD_PROJECT
      - run:
          name: Deploy to google cloud
          command: |
            gsutil -h "Cache-Control:public, max-age=0" rsync -d -r packages/extension-frontend/dist/frontend/ gs://diff-frontend
            gsutil iam ch allUsers:objectViewer gs://diff-frontend
      # - run:
      #     name: Deploy styleguide
      #     command: |
      #       gsutil -h "Cache-Control:public, max-age=0" rsync -d -r packages/shared-components/styleguide/ gs://diff-styles
      #       gsutil iam ch allUsers:objectViewer gs://diff-styles
  deploy-api:
    <<: *defaults
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - attach_workspace:
          at: packages
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "lerna.json"}}
      - run:
          command: |
            echo $CLIENT_SECRET | base64 --decode > ${HOME}/client-secret.json
            gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
      - run:
          name: Set project default
          command: gcloud config set project $GCLOUD_PROJECT
      - run:
          name: Deploy to google cloud
          command: |
            cd packages/gae-api
            gcloud app deploy app.yaml --quiet
  deploy-web:
    <<: *defaults
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - attach_workspace:
          at: packages
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "lerna.json"}}
      - run:
          command: |
            echo $CLIENT_SECRET | base64 --decode > ${HOME}/client-secret.json
            gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
      - run:
          name: Set project default
          command: gcloud config set project $GCLOUD_PROJECT
      - run:
          name: Deploy to google cloud
          command: |
            cd packages/gae-www-site
            gcloud app deploy app.yaml --quiet

workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - dependencies
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy-api:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy-web:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy-frontend:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy-chrome-extension:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
