version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: 
          command: |            
            sudo yarn global add lerna      
            lerna bootstrap
  test:      
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: sudo lerna exec -- yarn test
  deployExtension:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: sudo lerna exec -- yarn deploy    
  deployment:
    machine:
      environment:
        PYTHONPATH: ${PYTHONPATH}:${HOME}/google_appengine
        GCLOUD_PROJECT: "diff-204716"    
    steps:
      - run: 
          command: |
            echo $CLIENT_SECRET | base64 --decode > ${HOME}/client-secret.json
            gcloud --quiet components update app
            gcloud auth activate-service-account --key-file ${HOME}/client-secret.json        
            gcloud config set project $GCLOUD_PROJECT
            gcloud -q preview app deploy app.yaml --promote --version=1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployExtension:
          requires:
            - build
            - test
      - uploadFrontend:
          requires:
            - build
            - test
      - deployment
          requires:
            - build
            - test